name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate HTML
        run: npm install -g html-validate && html-validate index.html

      - name: Install ESLint
        run: npm install eslint --save-dev

      - name: Initialize ESLint configuration
        run: npx eslint --init

      - name: Run ESLint
        run: npm run lint 