name: CI

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Validate HTML
              run: npm install -g html-validate && html-validate index.html

            - name: Validate JS
              run: npm install eslint --save-dev
              run: npx eslint --init
              run: npm install -g eslint && eslint script.js
            
